import {
  Activity,
  Anchor,
  Apple,
  Beer,
  Bell,
  Bike,
  Bird,
  Building,
  Bus,
  Calendar,
  Camera,
  Car,
  Cat,
  ChefHat,
  CircleSlash,
  Clock,
  Cloud,
  CloudRain,
  Coffee,
  Cookie,
  Crown,
  CreditCard,
  CupSoda,
  Dog,
  DollarSign,
  Dumbbell,
  Egg,
  Eye,
  Factory,
  Film,
  Fish,
  Flower,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  IceCreamBowl,
  Key,
  Keyboard,
  Leaf,
  Lock,
  Mail,
  MessageCircle,
  Milk,
  Monitor,
  Moon,
  Mountain,
  Music,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Popcorn,
  Rabbit,
  Receipt,
  RefreshCcw,
  Sandwich,
  Settings,
  Ship,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Smile,
  Soup,
  Star,
  Stethoscope,
  Sun,
  Thermometer,
  ThumbsUp,
  Train,
  TreePine,
  TrendingDown,
  TrendingUp,
  Truck,
  Users,
  Utensils,
  Waves,
  Wheat,
  Wifi,
  Wine,
  Zap,
  ActivityIcon,
  Battery,
  Wind,
  Briefcase,
  Shield,
  Frown,
  Cake,
  Fuel,
  ParkingCircle,
  Route,
  MapPin,
  Navigation,
  Target,
  Trophy,
  Award,
  Cross,
  Syringe,
  Microscope,
  HeartHandshake,
  UserCheck,
  ShieldCheck,
  Compass,
  Flag,
  Mic,
  Radio,
  Tv,
  Play,
  Pause,
  Theater,
  Palette,
  BookOpen,
  Ticket,
  Clapperboard,
  Laptop,
  Tablet,
  HardDrive,
  Cpu,
  MemoryStick,
  Bluetooth,
  Speaker,
  Banknote,
  Coins,
  Wallet,
  Landmark,
  FileText,
  Calculator,
  BarChart3,
  PieChart,
  User,
  Presentation,
  Snowflake,
  Rainbow,
  Droplets,
  Flame,
  Package,
  Box,
  ShoppingCart,
  Scissors,
  Hammer,
  Wrench,
  Video,
  Volume2,
  Globe,
  Share,
  Link,
  AtSign,
  Hash,
  Send,
  Inbox,
  Bone,
  Turtle,
  Shell,
  Feather,
  Bug,
  Sprout,
  Flower2,
  Laugh,
  Angry,
  Meh,
  CheckCircle,
  XCircle,
  AlertCircle,
  HelpCircle,
  Folder,
  Archive,
  MapIcon,
} from 'lucide-react-native';

export const CATEGORY_ICONS = [
  {
    category: 'Food & Drink',
    icons: [
      { icon: Coffee, name: 'Coffee' },
      { icon: Wine, name: 'Wine' },
      { icon: Beer, name: 'Beer' },
      { icon: IceCreamBowl, name: 'Ice Cream' },
      { icon: Pizza, name: 'Pizza' },
      { icon: Apple, name: 'Apple' },
      { icon: Utensils, name: 'Utensils' },
      { icon: ChefHat, name: 'Chef Hat' },
      { icon: Sandwich, name: 'Sandwich' },
      { icon: Soup, name: 'Soup' },
      { icon: Cookie, name: 'Cookie' },
      { icon: Cake, name: 'Cake' },
      { icon: CupSoda, name: 'Soda' },
      { icon: Milk, name: 'Milk' },
      { icon: Wheat, name: 'Wheat' },
      { icon: Egg, name: 'Egg' },
    ],
  },
  {
    category: 'Transportation',
    icons: [
      { icon: Bike, name: 'Bike' },
      { icon: Bus, name: 'Bus' },
      { icon: Train, name: 'Train' },
      { icon: Truck, name: 'Truck' },
      { icon: Ship, name: 'Ship' },
      { icon: Anchor, name: 'Anchor' },
      { icon: Car, name: 'Car' },
      { icon: Plane, name: 'Plane' },
      { icon: MapPin, name: 'Map Pin' },
      { icon: Navigation, name: 'Navigation' },
      { icon: Fuel, name: 'Fuel' },
      { icon: ParkingCircle, name: 'Parking' },
      { icon: Route, name: 'Route' },
      { icon: Compass, name: 'Compass' },
      { icon: Flag, name: 'Flag' },
      { icon: MapIcon, name: 'Map' },
    ],
  },
  {
    category: 'Health & Fitness',
    icons: [
      { icon: Heart, name: 'Heart' },
      { icon: ActivityIcon, name: 'Fitness' },
      { icon: Pill, name: 'Pill' },
      { icon: Stethoscope, name: 'Stethoscope' },
      { icon: Thermometer, name: 'Thermometer' },
      { icon: Dumbbell, name: 'Dumbbell' },
      { icon: Activity, name: 'Activity' },
      { icon: Target, name: 'Target' },
      { icon: Trophy, name: 'Trophy' },
      { icon: Award, name: 'Award' },
      { icon: Cross, name: 'Cross' },
      { icon: Syringe, name: 'Syringe' },
      { icon: Microscope, name: 'Microscope' },
      { icon: HeartHandshake, name: 'Heart Handshake' },
      { icon: UserCheck, name: 'User Check' },
      { icon: ShieldCheck, name: 'Shield Check' },
    ],
  },
  {
    category: 'Entertainment',
    icons: [
      { icon: Music, name: 'Music' },
      { icon: Film, name: 'Film' },
      { icon: Gamepad2, name: 'Gamepad' },
      { icon: Headphones, name: 'Headphones' },
      { icon: Camera, name: 'Camera' },
      { icon: Popcorn, name: 'Popcorn' },
      { icon: Mic, name: 'Microphone' },
      { icon: Radio, name: 'Radio' },
      { icon: Tv, name: 'TV' },
      { icon: Play, name: 'Play' },
      { icon: Pause, name: 'Pause' },
      { icon: Theater, name: 'Theater' },
      { icon: Palette, name: 'Palette' },
      { icon: BookOpen, name: 'Book' },
      { icon: Ticket, name: 'Ticket' },
      { icon: Clapperboard, name: 'Clapperboard' },
    ],
  },
  {
    category: 'Technology',
    icons: [
      { icon: Smartphone, name: 'Smartphone' },
      { icon: Monitor, name: 'Monitor' },
      { icon: Keyboard, name: 'Keyboard' },
      { icon: Wifi, name: 'Wifi' },
      { icon: Battery, name: 'Battery' },
      { icon: Settings, name: 'Settings' },
      { icon: Laptop, name: 'Laptop' },
      { icon: Tablet, name: 'Tablet' },
      { icon: HardDrive, name: 'Hard Drive' },
      { icon: Cpu, name: 'CPU' },
      { icon: MemoryStick, name: 'Memory' },
      { icon: Zap, name: 'Lightning' },
      { icon: Bluetooth, name: 'Bluetooth' },
      { icon: Headphones, name: 'Headphones' },
      { icon: Speaker, name: 'Speaker' },
      { icon: Gamepad2, name: 'Gamepad' },
    ],
  },
  {
    category: 'Finance',
    icons: [
      { icon: DollarSign, name: 'Dollar' },
      { icon: CreditCard, name: 'Credit Card' },
      { icon: PiggyBank, name: 'Piggy Bank' },
      { icon: TrendingUp, name: 'Trending Up' },
      { icon: TrendingDown, name: 'Trending Down' },
      { icon: Receipt, name: 'Receipt' },
      { icon: Banknote, name: 'Banknote' },
      { icon: Coins, name: 'Coins' },
      { icon: Wallet, name: 'Wallet' },
      { icon: Landmark, name: 'Bank' },
      { icon: FileText, name: 'Document' },
      { icon: Calculator, name: 'Calculator' },
      { icon: BarChart3, name: 'Bar Chart' },
      { icon: PieChart, name: 'Pie Chart' },
      { icon: Briefcase, name: 'Briefcase' },
      { icon: Target, name: 'Target' },
    ],
  },
  {
    category: 'Work & Business',
    icons: [
      { icon: Briefcase, name: 'Briefcase' },
      { icon: Building, name: 'Building' },
      { icon: Factory, name: 'Factory' },
      { icon: Users, name: 'Users' },
      { icon: User, name: 'User' },
      { icon: GraduationCap, name: 'Graduation' },
      { icon: Presentation, name: 'Presentation' },
      { icon: Calendar, name: 'Calendar' },
      { icon: Clock, name: 'Clock' },
      { icon: Mail, name: 'Mail' },
      { icon: Phone, name: 'Phone' },
      { icon: FileText, name: 'Document' },
      { icon: Folder, name: 'Folder' },
      { icon: Archive, name: 'Archive' },
      { icon: Settings, name: 'Settings' },
      { icon: Shield, name: 'Shield' },
    ],
  },
  {
    category: 'Nature & Weather',
    icons: [
      { icon: Sun, name: 'Sun' },
      { icon: Moon, name: 'Moon' },
      { icon: Cloud, name: 'Cloud' },
      { icon: CloudRain, name: 'Rain' },
      { icon: Wind, name: 'Wind' },
      { icon: Leaf, name: 'Leaf' },
      { icon: TreePine, name: 'Tree' },
      { icon: Flower, name: 'Flower' },
      { icon: Mountain, name: 'Mountain' },
      { icon: Waves, name: 'Waves' },
      { icon: Snowflake, name: 'Snow' },
      { icon: Rainbow, name: 'Rainbow' },
      { icon: Zap, name: 'Lightning' },
      { icon: Thermometer, name: 'Thermometer' },
      { icon: Droplets, name: 'Droplets' },
      { icon: Flame, name: 'Flame' },
    ],
  },
  {
    category: 'Animals',
    icons: [
      { icon: PawPrint, name: 'Paw Print' },
      { icon: Dog, name: 'Dog' },
      { icon: Cat, name: 'Cat' },
      { icon: Fish, name: 'Fish' },
      { icon: Bird, name: 'Bird' },
      { icon: Rabbit, name: 'Rabbit' },
      { icon: Heart, name: 'Heart' },
      { icon: Bone, name: 'Bone' },
      { icon: Turtle, name: 'Turtle' },
      { icon: Shell, name: 'Shell' },
      { icon: Feather, name: 'Feather' },
      { icon: Bug, name: 'Bug' },
      { icon: Leaf, name: 'Leaf' },
      { icon: Sprout, name: 'Sprout' },
      { icon: TreePine, name: 'Pine Tree' },
      { icon: Flower2, name: 'Flower' },
    ],
  },
  {
    category: 'Objects',
    icons: [
      { icon: Gift, name: 'Gift' },
      { icon: Star, name: 'Star' },
      { icon: Crown, name: 'Crown' },
      { icon: Gem, name: 'Gem' },
      { icon: Key, name: 'Key' },
      { icon: Lock, name: 'Lock' },
      { icon: Shield, name: 'Shield' },
      { icon: Bell, name: 'Bell' },
      { icon: Clock, name: 'Clock' },
      { icon: Calendar, name: 'Calendar' },
      { icon: Package, name: 'Package' },
      { icon: Box, name: 'Box' },
      { icon: ShoppingCart, name: 'Cart' },
      { icon: Scissors, name: 'Scissors' },
      { icon: Hammer, name: 'Hammer' },
      { icon: Wrench, name: 'Wrench' },
    ],
  },
  {
    category: 'Communication',
    icons: [
      { icon: Mail, name: 'Mail' },
      { icon: Phone, name: 'Phone' },
      { icon: MessageCircle, name: 'Message' },
      { icon: Eye, name: 'Eye' },
      { icon: Video, name: 'Video' },
      { icon: Mic, name: 'Microphone' },
      { icon: Volume2, name: 'Volume' },
      { icon: Wifi, name: 'Wifi' },
      { icon: Globe, name: 'Globe' },
      { icon: Share, name: 'Share' },
      { icon: Link, name: 'Link' },
      { icon: AtSign, name: 'At Sign' },
      { icon: Hash, name: 'Hash' },
      { icon: Send, name: 'Send' },
      { icon: Inbox, name: 'Inbox' },
      { icon: Archive, name: 'Archive' },
    ],
  },
  {
    category: 'Emotions',
    icons: [
      { icon: Smile, name: 'Smile' },
      { icon: Frown, name: 'Frown' },
      { icon: ThumbsUp, name: 'Thumbs Up' },
      { icon: Heart, name: 'Heart' },
      { icon: Zap, name: 'Lightning' },
      { icon: Laugh, name: 'Laugh' },
      { icon: Angry, name: 'Angry' },
      { icon: Meh, name: 'Meh' },
      { icon: Star, name: 'Star' },
      { icon: Award, name: 'Award' },
      { icon: Trophy, name: 'Trophy' },
      { icon: Target, name: 'Target' },
      { icon: CheckCircle, name: 'Check' },
      { icon: XCircle, name: 'X' },
      { icon: AlertCircle, name: 'Alert' },
      { icon: HelpCircle, name: 'Help' },
    ],
  },
];
