export const CATEGORY_COLORS = [
  { hex: '#FFFFFF', name: 'White' },
  { hex: '#FF0000', name: 'Bright Red' },
  { hex: '#FF4500', name: 'Orange Red' },
  { hex: '#FF6347', name: 'Coral' },
  { hex: '#FF8C00', name: 'Dark Orange' },
  { hex: '#FFD700', name: 'Gold' },
  { hex: '#FFFF00', name: 'Bright Yellow' },
  { hex: '#ADFF2F', name: 'Green Yellow' },
  { hex: '#00FF00', name: 'Lime Green' },
  { hex: '#00FF7F', name: 'Spring Green' },
  { hex: '#00FFFF', name: 'Cyan' },
  { hex: '#00BFFF', name: 'Deep Sky Blue' },
  { hex: '#1E90FF', name: 'Dodger Blue' },
  { hex: '#0000FF', name: 'Bright Blue' },
  { hex: '#4B0082', name: 'Indigo' },
  { hex: '#8A2BE2', name: 'Blue Violet' },
  { hex: '#9932CC', name: 'Dark Orchid' },
  { hex: '#FF1493', name: 'Deep Pink' },
  { hex: '#FF69B4', name: 'Hot Pink' },
  { hex: '#FFC0CB', name: 'Light Pink' },
];
